targetScope = 'resourceGroup'

@description('Enter the name of the existing ACR instance to deploy to, if applicable.')
@minLength(5)
@maxLength(50)
param containerRegistryName string

@description('Subscription ID used only for scoping an existing ACR instance and ACR role assignments.')
param targetSubscriptionId string = subscription().subscriptionId

@description('Resource group of the existing ACR instance, if applicable.')
param acrResourceGroupName string = ''

@description('Azure region for all resources.')
param location string = resourceGroup().location

@description('Globally unique Key Vault name.')
param keyVaultName string = 'kv-cgr-${uniqueString(resourceGroup().id)}'

@description('Container Apps Managed Environment name.')
param containerAppEnvironmentName string = 'cgr-container-env'

@description('Container App name.')
param containerAppName string = 'cgr-image-copy-app'

@description('HTTPS URL of the Git repo containing the Dockerfile.')
param gitRepoUrl string = 'https://github.com/justinprince/platform-examples'

@description('Git branch to build from.')
param gitRepoBranch string = 'main'

@description('Relative path to the Dockerfile within the repo.')
param dockerfilePath string = 'Dockerfile'

@description('Docker build context path relative to repo root.')
param gitRepoContextPath string = 'claude-image-copy-acr-blueprint'

@secure()
@description('Chainguard OIDC token generated by the user with chainctl and stored in Key Vault during deployment.')
param chainguardOidcToken string

@description('Chainguard API endpoint.')
param apiEndpoint string = 'https://console-api.enforce.dev'

@description('Chainguard issuer URL.')
param issuerUrl string = 'https://issuer.enforce.dev'

@description('Chainguard organization name used as GROUP_NAME.')
param chainguardOrg string = 'justin.prince'

@description('Chainguard group identifier used as GROUP.')
param chainguardGroup string = 'justin.prince'

@description('Chainguard identity used as IDENTITY.')
param chainguardIdentity string = 'taco'

@description('Skip referrer tags such as signatures and attestations.')
param ignoreReferrers bool = true

@description('Verify Chainguard image signatures before copying.')
param verifySignatures bool = false

var acrTaskName = 'build-cgr-image-copy'
var imageName = 'cgr-image-copy:v1'
var chainguardSecretName = 'chainguard-oidc-token'
var acrPullRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
var acrPushRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '8311e382-0749-4cb8-b61a-304f252e45ec')
var kvSecretsUserRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
var contributorRoleDefinitionId = subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
var appIdentityName = '${containerAppName}-identity'
var scriptIdentityName = 'script-runner-${uniqueString(resourceGroup().id)}'
var deploymentScriptName = 'trigger-acr-task-build'
var destinationRepository = '${containerRegistryName}.azurecr.io/cgr-image-copy'
var appIdentityResourceId = resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', appIdentityName)
var scriptIdentityResourceId = resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', scriptIdentityName)
var useExistingAcr = !empty(acrResourceGroupName)
var effectiveAcrSubscriptionId = useExistingAcr ? targetSubscriptionId : subscription().subscriptionId
var effectiveAcrResourceGroupName = useExistingAcr ? acrResourceGroupName : resourceGroup().name

resource targetAcrResourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' existing = {
  scope: subscription(effectiveAcrSubscriptionId)
  name: effectiveAcrResourceGroupName
}

resource targetRegistry 'Microsoft.ContainerRegistry/registries@2023-07-01' existing = {
  scope: targetAcrResourceGroup
  name: containerRegistryName
}

resource containerRegistry 'Microsoft.ContainerRegistry/registries@2023-07-01' = if (!useExistingAcr) {
  name: containerRegistryName
  location: location
  sku: {
    name: 'Standard'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    adminUserEnabled: false
    publicNetworkAccess: 'Enabled'
    zoneRedundancy: 'Disabled'
  }
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enabledForDeployment: false
    enabledForDiskEncryption: false
    enabledForTemplateDeployment: false
    publicNetworkAccess: 'Enabled'
  }
}

resource keyVaultSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  name: '${keyVaultName}/${chainguardSecretName}'
  properties: {
    value: chainguardOidcToken
    attributes: {
      enabled: true
    }
    contentType: 'text/plain'
  }
  dependsOn: [
    keyVault
  ]
}

resource appIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: appIdentityName
  location: location
}

resource scriptIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: scriptIdentityName
  location: location
}

resource managedEnvironment 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: containerAppEnvironmentName
  location: location
  properties: {}
}

resource acrPullRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: targetRegistry
  name: guid(targetRegistry.id, appIdentityName, 'acrPull')
  properties: {
    roleDefinitionId: acrPullRoleDefinitionId
    principalId: appIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
  dependsOn: [
    appIdentity
    containerRegistry
  ]
}

resource acrPushRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: targetRegistry
  name: guid(targetRegistry.id, appIdentityName, 'acrPush')
  properties: {
    roleDefinitionId: acrPushRoleDefinitionId
    principalId: appIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
  dependsOn: [
    appIdentity
    containerRegistry
  ]
}

resource keyVaultSecretsUserRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: keyVault
  name: guid(keyVault.id, appIdentityName, 'kvSecrets')
  properties: {
    roleDefinitionId: kvSecretsUserRoleDefinitionId
    principalId: appIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

resource scriptContributorRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: targetRegistry
  name: guid(targetRegistry.id, scriptIdentityName, 'scriptContrib')
  properties: {
    roleDefinitionId: contributorRoleDefinitionId
    principalId: scriptIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
  dependsOn: [
    scriptIdentity
    containerRegistry
  ]
}

resource acrTask 'Microsoft.ContainerRegistry/registries/tasks@2019-06-01-preview' = {
  name: '${containerRegistryName}/${acrTaskName}'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    platform: {
      os: 'Linux'
      architecture: 'amd64'
    }
    agentConfiguration: {
      cpu: 2
    }
    step: {
      type: 'Docker'
      dockerFilePath: dockerfilePath
      contextPath: '${gitRepoUrl}#${gitRepoBranch}:${gitRepoContextPath}'
      imageNames: [
        imageName
      ]
      isPushEnabled: true
      noCache: false
      arguments: []
    }
    trigger: {
      sourceTriggers: []
      timerTriggers: []
      baseImageTrigger: {
        name: 'defaultBaseimageTriggerName'
        baseImageTriggerType: 'Runtime'
        updateTriggerPayloadType: 'Default'
        status: 'Enabled'
      }
    }
    isSystemTask: false
    status: 'Enabled'
    timeout: 3600
  }
  dependsOn: [
    containerRegistry
  ]
}

resource deploymentScript 'Microsoft.Resources/deploymentScripts@2023-08-01' = {
  name: deploymentScriptName
  location: location
  kind: 'AzureCLI'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${scriptIdentityResourceId}': {}
    }
  }
  properties: {
    azCliVersion: '2.59.0'
    retentionInterval: 'PT2H'
    timeout: 'PT10M'
    cleanupPreference: 'OnSuccess'
    environmentVariables: [
      {
        name: 'REGISTRY_NAME'
        value: containerRegistryName
      }
      {
        name: 'TASK_NAME'
        value: acrTaskName
      }
    ]
    scriptContent: '''
      set -e

      echo "[deploymentScript] Triggering ACR Task: $TASK_NAME on registry: $REGISTRY_NAME"

      RUN_ID=$(az acr task run \
        --registry "$REGISTRY_NAME" \
        --name "$TASK_NAME" \
        --no-wait \
        --query runId \
        --output tsv)

      if [ -z "$RUN_ID" ]; then
        echo "[deploymentScript] Failed to retrieve run ID from az acr task run."
        exit 1
      fi

      echo "[deploymentScript] Task queued with run ID: $RUN_ID"

      MAX_WAIT=420
      ELAPSED=0
      INTERVAL=15

      while [ $ELAPSED -lt $MAX_WAIT ]; do
        STATUS=$(az acr task show-run \
          --registry "$REGISTRY_NAME" \
          --run-id "$RUN_ID" \
          --query status \
          --output tsv)

        if [ -z "$STATUS" ]; then
          echo "[deploymentScript] Empty status returned for run $RUN_ID"
          exit 1
        fi

        echo "[deploymentScript] Run $RUN_ID status: $STATUS (${ELAPSED}s elapsed)"

        if [ "$STATUS" = "Succeeded" ]; then
          echo "[deploymentScript] Build succeeded. Image cgr-image-copy:v1 is ready."
          echo "{\"runId\":\"$RUN_ID\",\"status\":\"Succeeded\"}" > $AZ_SCRIPTS_OUTPUT_PATH
          exit 0
        fi

        if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Canceled" ] || [ "$STATUS" = "Error" ] || [ "$STATUS" = "Timeout" ]; then
          echo "[deploymentScript] Build $STATUS. Fetching logs:"
          az acr task logs --registry "$REGISTRY_NAME" --run-id "$RUN_ID" || true
          exit 1
        fi

        sleep $INTERVAL
        ELAPSED=$((ELAPSED + INTERVAL))
      done

      echo "[deploymentScript] Timed out after ${MAX_WAIT}s while waiting for run $RUN_ID."
      az acr task show-run --registry "$REGISTRY_NAME" --run-id "$RUN_ID" || true
      exit 1
      '''
  }
  dependsOn: [
    acrTask
    scriptIdentity
    containerRegistry
    scriptContributorRoleAssignment
  ]
}

resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: containerAppName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${appIdentityResourceId}': {}
    }
  }
  properties: {
    managedEnvironmentId: managedEnvironment.id
    configuration: {
      secrets: [
        {
          name: chainguardSecretName
          keyVaultUrl: keyVaultSecret.properties.secretUri
          identity: appIdentityResourceId
        }
      ]
      registries: [
        {
          server: '${containerRegistryName}.azurecr.io'
          identity: appIdentityResourceId
        }
      ]
      ingress: {
        external: false
        targetPort: 8080
        transport: 'auto'
      }
    }
    template: {
      containers: [
        {
          name: 'cgr-image-copy'
          image: '${containerRegistryName}.azurecr.io/${imageName}'
          env: [
            {
              name: 'OIDC_TOKEN'
              secretRef: chainguardSecretName
            }
            {
              name: 'API_ENDPOINT'
              value: apiEndpoint
            }
            {
              name: 'ISSUER_URL'
              value: issuerUrl
            }
            {
              name: 'GROUP_NAME'
              value: chainguardOrg
            }
            {
              name: 'GROUP'
              value: chainguardGroup
            }
            {
              name: 'IDENTITY'
              value: chainguardIdentity
            }
            {
              name: 'DST_REPO'
              value: destinationRepository
            }
            {
              name: 'ACR_REGISTRY'
              value: '${containerRegistryName}.azurecr.io'
            }
            {
              name: 'IGNORE_REFERRERS'
              value: string(ignoreReferrers)
            }
            {
              name: 'VERIFY_SIGNATURES'
              value: string(verifySignatures)
            }
            {
              name: 'PORT'
              value: '8080'
            }
          ]
          resources: {
            cpu: json('0.5')
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 1
        maxReplicas: 1
      }
    }
  }
  dependsOn: [
    managedEnvironment
    appIdentity
    keyVaultSecret
    containerRegistry
    keyVault
    deploymentScript
    acrPullRoleAssignment
    acrPushRoleAssignment
    keyVaultSecretsUserRoleAssignment
  ]
}

output containerRegistryLoginServer string = targetRegistry.properties.loginServer
output keyVaultNameOutput string = keyVaultName
output keyVaultUri string = keyVault.properties.vaultUri
output containerAppFqdn string = containerApp.properties.configuration.ingress.fqdn
output acrTaskRunId string = deploymentScript.properties.outputs.runId
output updateSecretCommand string = 'az keyvault secret set --vault-name ${keyVaultName} --name ${chainguardSecretName} --value <YOUR_TOKEN>'
